USE [master]
GO

/****** Object:  Database [DM_Reservas]    Script Date: 12/12/2019 15:05:34 ******/
CREATE DATABASE [DM_Reservas]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DM_Reservas', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\DM_Reservas.mdf' , SIZE = 512MB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DM_Reservas_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\LOG\DM_Reservas_log.ldf' , SIZE = 512MB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
COLLATE Latin1_General_CI_AS
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DM_Reservas].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DM_Reservas] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DM_Reservas] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DM_Reservas] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DM_Reservas] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DM_Reservas] SET ARITHABORT OFF 
GO

ALTER DATABASE [DM_Reservas] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DM_Reservas] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DM_Reservas] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DM_Reservas] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DM_Reservas] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DM_Reservas] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DM_Reservas] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DM_Reservas] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DM_Reservas] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DM_Reservas] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DM_Reservas] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DM_Reservas] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DM_Reservas] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DM_Reservas] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DM_Reservas] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DM_Reservas] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DM_Reservas] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DM_Reservas] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DM_Reservas] SET  MULTI_USER 
GO

ALTER DATABASE [DM_Reservas] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DM_Reservas] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DM_Reservas] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DM_Reservas] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DM_Reservas] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DM_Reservas] SET QUERY_STORE = OFF
GO

USE [DM_Reservas]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [DM_Reservas] SET  READ_WRITE 
GO


